name: ChatBlacklistWordsPlugin
version: '1.0-SNAPSHOT'
main: filip.hardcorecode.chatBlacklistWordsPlugin.ChatBlacklistWordsPlugin
api-version: '1.20'
commands:
  blacklistwords:
    permission: blacklistwords.admin.use